### PR TITLE
fix(merge): ensure undefined is assigned when merging partial mock

### LINKED ISSUE #746: Hydrated mock with undefined object values as parameter
### Subject of the issue
I noticed on subtle change between the `createMock` and `createHydratedMock` functions.
Following my last comment https://github.com/Typescript-TDD/ts-auto-mock/issues/699.
Should fix https://github.com/Sonia-corporation/sonia-discord/pull/1383

### Your environment
* ts-auto-mock version: 3.2.1
* typescript version: 4.2.4
* node version: 14.17.0
* npm version: 7.12.1
* jest-ts-auto-mock: 2.0.0

### Steps to reproduce

No problem, the features will stay undefined.
```typescript
channel = createMock<IFirebaseGuildChannelV2>({
  features: undefined,
  id: `dummy-id`,
  version: FirebaseGuildChannelVersionEnum.V2,
});
```

The features will have random values.
```typescript
channel = createHydratedMock<IFirebaseGuildChannelV2>({
  features: undefined,
  id: `dummy-id`,
  version: FirebaseGuildChannelVersionEnum.V2,
});
```

### Expected behaviour
Same behaviour between `createMock` and `createHydratedMock` functions which replace the `undefined` value as expected (so `createMock` is better IMO).

### Actual behaviour
The `createHydratedMock` function will ignore the given object value if `undefined` instead of using the value to fill the mock.

### PR DESCRIPTION
**Pull request by Pmyl**
Thank you for your contribution to ts auto mock repo. 
Before submitting this PR, please make sure:

- [x] Your code builds clean without any errors or warnings
- [x] You have added tests

[lodash `merge` and `mergeWith` skip undefined by design](https://lodash.com/docs/4.17.15#merge), this doesn't match our requirement of applying the partial mock to the generated mock.
This PR updates the merge functionality to handle the case with `undefined` and fixes #746

### CODE REVIEW

**Review by uittorio — APPROVED** [review]
LGTM!!!

**Comment by C0ZEN** [comment]
@Pmyl @uittorio thank you 🎉

**Comment by uittorio** [comment]
@C0ZEN thank you for the contribution! We wouldnt find these bugs if no one uses these functionalities extensively!!!

**Pull request merged**
